@startuml

title __KP's Class Diagram__\n















































  


  com.example.kp.AdminWindow -up-|> com.example.kp.Window
  com.example.kp.AdminWindow o-- com.example.kp.Database.Help : help
  com.example.kp.AdminWindow o-- com.example.kp.Database.LK : lk

  com.example.kp.ChatWindom -up-|> com.example.kp.Window
  com.example.kp.ChatWindom o-- com.example.kp.Database.Chat : chat
  com.example.kp.Login o-- com.example.kp.Database.DbHandler : databaseWork
  com.example.kp.Login o-- com.example.kp.Database.LK : lk
  com.example.kp.Main -up-|> javafx.application.Application
  com.example.kp.MainController o-- com.example.kp.Database.LK : lk

  com.example.kp.NewHelp -up-|> com.example.kp.Window
  com.example.kp.NewHelp o-- com.example.kp.Database.Help : help

  com.example.kp.NewWork -up-|> com.example.kp.Window
  com.example.kp.NewWork o-- com.example.kp.Database.Help : help

  com.example.kp.PolWindow -up-|> com.example.kp.Window
  com.example.kp.PolWindow o-- com.example.kp.Database.Help : help
  com.example.kp.Window o-- com.example.kp.Database.LK : lk

  com.example.kp.WorkerWindom -up-|> com.example.kp.Window
  com.example.kp.WorkerWindom o-- com.example.kp.Database.Help : help
  com.example.kp.Database.Chat -up-|> com.example.kp.Database.DbHandler
    com.example.kp.Database.Help -up-|> com.example.kp.Database.DbHandler
    com.example.kp.Database.LK -up-|> com.example.kp.Database.DbHandler
    com.example.kp.Database.Master -up-|> com.example.kp.Database.DbHandler
    com.example.kp.Database.Pol -up-|> com.example.kp.Database.DbHandler


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
